import {
  CurrentSetupScene,
  CURRENT_SETUP_SCENE_DURATION,
  CurrentSetupScene4,
  CURRENT_SETUP_SCENE_4_DURATION,
  CurrentSetupScene5,
  CURRENT_SETUP_SCENE_5_DURATION,
  CurrentSetupScene6,
  CURRENT_SETUP_SCENE_6_DURATION,
  CurrentSetupScene7,
  CURRENT_SETUP_SCENE_7_DURATION,
  CurrentSetupScene8,
  CURRENT_SETUP_SCENE_8_DURATION,
  CurrentSetupScene9,
  CURRENT_SETUP_SCENE_9_DURATION,
  CurrentSetupScene10,
  CURRENT_SETUP_SCENE_10_DURATION,
  FlakeEntryGraphScene,
  FLAKE_ENTRY_GRAPH_DURATION,
  FlakeFileScene,
  FLAKE_FILE_SCENE_DURATION,
} from "../scenes/CurrentSetup";
import type { RemotionModule } from "./types";

const BASE_WIDTH = 3440;
const BASE_HEIGHT = 1440;
const BASE_FPS = 30;

export const currentSetupModule: RemotionModule = {
  id: "current-setup",
  title: "Current Setup",
  compositions: [
    {
      id: "current-setup-overview",
      component: CurrentSetupScene,
      durationInFrames: CURRENT_SETUP_SCENE_DURATION,
      fps: BASE_FPS,
      width: BASE_WIDTH,
      height: BASE_HEIGHT,
    },
    {
      id: "current-setup-flake-entry-graph",
      component: FlakeEntryGraphScene,
      durationInFrames: FLAKE_ENTRY_GRAPH_DURATION,
      fps: BASE_FPS,
      width: BASE_WIDTH,
      height: BASE_HEIGHT,
    },
    {
      id: "current-setup-flake-file",
      component: FlakeFileScene,
      durationInFrames: FLAKE_FILE_SCENE_DURATION,
      fps: BASE_FPS,
      width: BASE_WIDTH,
      height: BASE_HEIGHT,
    },
    {
      id: "current-setup-scene-4",
      component: CurrentSetupScene4,
      durationInFrames: CURRENT_SETUP_SCENE_4_DURATION,
      fps: BASE_FPS,
      width: BASE_WIDTH,
      height: BASE_HEIGHT,
    },
    {
      id: "current-setup-scene-5",
      component: CurrentSetupScene5,
      durationInFrames: CURRENT_SETUP_SCENE_5_DURATION,
      fps: BASE_FPS,
      width: BASE_WIDTH,
      height: BASE_HEIGHT,
    },
    {
      id: "current-setup-scene-6",
      component: CurrentSetupScene6,
      durationInFrames: CURRENT_SETUP_SCENE_6_DURATION,
      fps: BASE_FPS,
      width: BASE_WIDTH,
      height: BASE_HEIGHT,
    },
    {
      id: "current-setup-scene-7",
      component: CurrentSetupScene7,
      durationInFrames: CURRENT_SETUP_SCENE_7_DURATION,
      fps: BASE_FPS,
      width: BASE_WIDTH,
      height: BASE_HEIGHT,
    },
    {
      id: "current-setup-scene-8",
      component: CurrentSetupScene8,
      durationInFrames: CURRENT_SETUP_SCENE_8_DURATION,
      fps: BASE_FPS,
      width: BASE_WIDTH,
      height: BASE_HEIGHT,
    },
    {
      id: "current-setup-scene-9",
      component: CurrentSetupScene9,
      durationInFrames: CURRENT_SETUP_SCENE_9_DURATION,
      fps: BASE_FPS,
      width: BASE_WIDTH,
      height: BASE_HEIGHT,
    },
    {
      id: "current-setup-scene-10",
      component: CurrentSetupScene10,
      durationInFrames: CURRENT_SETUP_SCENE_10_DURATION,
      fps: BASE_FPS,
      width: BASE_WIDTH,
      height: BASE_HEIGHT,
    },
  ],
};
