import {
  // NixvimBlockBuildScene,
  NixvimComparisonIntroScene,
  NixvimDefinitionScene,
  NixvimSpecialScene,
  NixvimSpecialSceneV2,
  NixvimProsConsScene,
  NixCatsIntroScene,
  NixCatsSpecialScene,
  NixCatsProsConsScene,
  NvfIntroScene,
  NvfAdvantagesScene,
  NvfProsConsScene,
  NvfProsConsSceneV2,
  EaseOfUseOutroScene,
  NixvimConclusionIntroScene,
  // NIXVIM_BLOCK_BUILD_DURATION,
  NIXVIM_COMPARISON_INTRO_DURATION,
  NIXVIM_DEFINITION_DURATION,
  NIXVIM_SPECIAL_DURATION,
  NIXVIM_SPECIAL_V2_DURATION,
  NIXVIM_PROS_CONS_DURATION,
  NIXCATS_INTRO_DURATION,
  NIXCATS_SPECIAL_DURATION,
  NIXCATS_PROS_CONS_DURATION,
  NVF_INTRO_DURATION,
  NVF_ADVANTAGES_DURATION,
  NVF_PROS_CONS_DURATION,
  NVF_PROS_CONS_V2_DURATION,
  EASE_OF_USE_OUTRO_DURATION,
  NIXVIM_CONCLUSION_INTRO_DURATION,
  NIXVIM_FLAKE_INTRO_DURATION,
  NixvimFlakeIntroScene,
} from "../scenes/Nixvim";
import type { RemotionModule } from "./types";

const BASE_WIDTH = 3440;
const BASE_HEIGHT = 1440;
const BASE_FPS = 30;

export const nixvimModule: RemotionModule = {
  id: "nixvim",
  title: "Nixvim Build",
  compositions: [
    {
      id: "nixvim-comparison-intro",
      component: NixvimComparisonIntroScene,
      durationInFrames: NIXVIM_COMPARISON_INTRO_DURATION,
      fps: BASE_FPS,
      width: BASE_WIDTH,
      height: BASE_HEIGHT,
    },
    {
      id: "nixvim-definition",
      component: NixvimDefinitionScene,
      durationInFrames: NIXVIM_DEFINITION_DURATION,
      fps: BASE_FPS,
      width: BASE_WIDTH,
      height: BASE_HEIGHT,
    },
    {
      id: "nixvim-special",
      component: NixvimSpecialScene,
      durationInFrames: NIXVIM_SPECIAL_DURATION,
      fps: BASE_FPS,
      width: BASE_WIDTH,
      height: BASE_HEIGHT,
    },
    {
      id: "nixvim-special-v2",
      component: NixvimSpecialSceneV2,
      durationInFrames: NIXVIM_SPECIAL_V2_DURATION,
      fps: BASE_FPS,
      width: BASE_WIDTH,
      height: BASE_HEIGHT,
    },
    {
      id: "nixvim-pros-cons",
      component: NixvimProsConsScene,
      durationInFrames: NIXVIM_PROS_CONS_DURATION,
      fps: BASE_FPS,
      width: BASE_WIDTH,
      height: BASE_HEIGHT,
    },
    {
      id: "nixcats-intro",
      component: NixCatsIntroScene,
      durationInFrames: NIXCATS_INTRO_DURATION,
      fps: BASE_FPS,
      width: BASE_WIDTH,
      height: BASE_HEIGHT,
    },
    {
      id: "nixcats-special",
      component: NixCatsSpecialScene,
      durationInFrames: NIXCATS_SPECIAL_DURATION,
      fps: BASE_FPS,
      width: BASE_WIDTH,
      height: BASE_HEIGHT,
    },
    {
      id: "nixcats-pros-cons",
      component: NixCatsProsConsScene,
      durationInFrames: NIXCATS_PROS_CONS_DURATION,
      fps: BASE_FPS,
      width: BASE_WIDTH,
      height: BASE_HEIGHT,
    },
    {
      id: "nvf-intro",
      component: NvfIntroScene,
      durationInFrames: NVF_INTRO_DURATION,
      fps: BASE_FPS,
      width: BASE_WIDTH,
      height: BASE_HEIGHT,
    },
    {
      id: "nvf-advantages",
      component: NvfAdvantagesScene,
      durationInFrames: NVF_ADVANTAGES_DURATION,
      fps: BASE_FPS,
      width: BASE_WIDTH,
      height: BASE_HEIGHT,
    },
    {
      id: "nvf-pros-cons",
      component: NvfProsConsScene,
      durationInFrames: NVF_PROS_CONS_DURATION,
      fps: BASE_FPS,
      width: BASE_WIDTH,
      height: BASE_HEIGHT,
    },
    {
      id: "nvf-pros-cons-v2",
      component: NvfProsConsSceneV2,
      durationInFrames: NVF_PROS_CONS_V2_DURATION,
      fps: BASE_FPS,
      width: BASE_WIDTH,
      height: BASE_HEIGHT,
    },
    {
      id: "ease-of-use-outro",
      component: EaseOfUseOutroScene,
      durationInFrames: EASE_OF_USE_OUTRO_DURATION,
      fps: BASE_FPS,
      width: BASE_WIDTH,
      height: BASE_HEIGHT,
    },
    {
      id: "nixvim-conclusion-intro",
      component: NixvimConclusionIntroScene,
      durationInFrames: NIXVIM_CONCLUSION_INTRO_DURATION,
      fps: BASE_FPS,
      width: BASE_WIDTH,
      height: BASE_HEIGHT,
    },
    {
      id: "nixvim-flake-intro",
      component: NixvimFlakeIntroScene,
      durationInFrames: NIXVIM_FLAKE_INTRO_DURATION,
      fps: BASE_FPS,
      width: BASE_WIDTH,
      height: BASE_HEIGHT,
    },
    // {
    //   id: "nixvim-block-build",
    //   component: NixvimBlockBuildScene,
    //   durationInFrames: NIXVIM_BLOCK_BUILD_DURATION,
    //   fps: BASE_FPS,
    //   width: BASE_WIDTH,
    //   height: BASE_HEIGHT,
    // },
  ],
};
